### ISSUE TITLE
Bug - player movement controls get stuck in certain conditions

### ISSUE THREAD

**Issue by Monomancer** [ConnorMulqueen/Geesenado#105]
Sometimes during the game, the player movement will get locked in a certain direction, for example if I am pressing down D and the conditions that trigger the bug are met, the player will continually walk right.
When the player movement is stuck, pressing the opposite direction does nothing (sometimes), but you can still move along the other axis. It is persistent across game restarts.  I originally discovered this through normal game-play, although it may only able to be replicated on my specific system.
  

How to replicate:  
This bug seems to happens sometimes when clicking and dragging on certain parts of the screen while moving. The mouse cursor turns into a hand cursor when done properly (while clicking and dragging)  
  
Exact steps to replicate:
  * start the game and move down and to the left of the dark blue area (directly below the starting area)  
  * once you are in that area, click rapidly and drag the mouse around slightly while clicking (click on and around  the three things in the grassy area in the dark blue area)  
  * at the same time, also press any of the movement keys down
  * if your player begins to drift  in the direction you pressed, even after releasing the key, then you have successfully replicated the bug  
  * you may use the pause menu to restart the game in order to see that the bug is persistent across games

Specs: 

Run on Unity WebGL player, Chrome Version 65.0.3325.181, 64 bits.
OS: Ubuntu 16.04.4

**Comment by jaredgav** [comment]
Sounds like it could just be a browser issue, as dragging is not a feature in this game. We will look into it.

**Comment by KDub18** [comment]
@jaredgav  I tried to recreate this bug a few times but to no avail. I will further look into it but this may be a browser issue after all.
