### ISSUE TITLE
Feature Request: Geese Graphics

### ISSUE THREAD

**Issue by justynth** [ConnorMulqueen/Geesenado#108]
I ran your game. Since the name of the game is geesenado I was expecting geese to show up. The graphics are just primarily blocks when I run the game. Not sure if this is intended or if I need to download specific software to view graphics in the game. If I need to download something make sure it is clear. If these are the intended graphics then they should be updated to include geese at the edge of the map.

**Comment by jaredgav** [comment]
Yes we have this coming in a soon to be future release. I think you will enjoy it!

**Comment by jaredgav** [comment]
This was completed in a previous pull request.
