### ISSUE TITLE
[Trivial Bug] Player is getting stuck in O'brian Hall

### ISSUE THREAD

**Issue by arturoto** [ConnorMulqueen/Geesenado#110]
In the bottom corner of O'brian Hall the player is getting stuck. When at an angle the player cannot move from the bottom wall of the map and the southern wall O'brian.

<img width="363" alt="screen shot 2018-04-20 at 12 54 45 am" src="https://user-images.githubusercontent.com/16159696/39031631-7104e1ca-4437-11e8-8224-ad47839b6ca8.png">

<img width="358" alt="screen shot 2018-04-20 at 12 54 25 am" src="https://user-images.githubusercontent.com/16159696/39031596-380fd10e-4437-11e8-81d2-92123a90e025.png">

**Comment by jaredgav** [comment]
How would we replicate this?

**Comment by jaredgav** [comment]
For instance, were you using webgl, or the .exe to play? Did anything specific happen before this occured? Does it happen every time you play?

**Comment by arturoto** [comment]
I was testing the game within unity. This happened a couple of times when the player was tilted at an angle. If i collided with a sharp corner the player would tilt a little bit. Once tilted the player would not fit in through that narrow walkway.

**Comment by jaredgav** [comment]
Ok thanks, we will take a look!

**Comment by KDub18** [comment]
Hi all, this is probably an issue with some colliders. I will fix this soon!

**Comment by KDub18** [comment]
Bug fixed!
