### ISSUE TITLE
Feature request: Add charging indicator to textboox

### ISSUE THREAD

**Issue by briankarUB** [ConnorMulqueen/Geesenado#113]
As it stands, there's no indication that you're charging the textbook up to throw it. Maybe add some sort of bar above your player to show this?

**Comment by jaredgav** [comment]
I 100% agree, I had started working on this before and didn't get around to finishing it. Thank you! I'll work on it

**Comment by jaredgav** [comment]
All set! In the next release you can now see the charge indicator
