### ISSUE TITLE
Make a NPC stop running at the player after an extended period of time.

### ISSUE THREAD

**Issue by ConnorMulqueen** [ConnorMulqueen/Geesenado#45]
Currently, once the Player gets within "_aggroRadius" of the NPC, our "_aggroFlag" is set to TRUE and the NPC will start running towards the Player endlessly. This should be changed to stop running after 10 seconds of time elapsed.

Things to consider:

- The file you will work in is **NPC.cs**
- The **'_aggroFlag'** is flipped within the method **movement()**, you should keep track of the time that this boolean is flipped. [Here's documentation to help with that](https://docs.unity3d.com/ScriptReference/Time-time.html)
- After 10 seconds of this boolean being flipped, you should flip it back to FALSE

If you have questions, check the NPC/AI section of our wiki, or feel free to reach out to me on our Gitter!

**Comment by ChineSEngineer** [comment]
Hi, I am assigned to do the help wanted part of your team. But I can't find the main scene file of your project after I clone it.

**Comment by jaredgav** [comment]
It's called sampkeScene in the assets folder

**Comment by jaredgav** [comment]
Sample*

**Comment by ChineSEngineer** [comment]
Thanks! 
1. What is the meaning of  _currentlyDodging flag and dodge() function?
2. When the NPC stop chasing the player, what should the NPC do then? dodge()?

**Comment by ConnorMulqueen** [comment]
Hey!

for #1 - the _currentlyDodging flag is used to represent if the NPC is currently dodging or not. This is used when dodging incoming projectiles, once it is true the NPC will dodge in a certain direction for .3 seconds. If we didn't have this flag, when a projectile came in range of _dodgeRadius the NPC would continously randomize a direction to dodge (left or right) and visibly stutter in-game. Though, you shouldn't have to worry about this for your issue.

for #2 - I would like the NPC to revert back to its previous state, the passiveWalk() method. Once you flip _aggroFlag back to false -- the movement() method will handle the rest for you! It calls passiveWalk() on line 94 when _aggroFlag is false.

**Comment by ChineSEngineer** [comment]
I saw you measure the distance between NPC and Player when aggroFlag=False. However, it seems that even if the enemy is very very far from the player, the enemy will still move towards the player. Am I right?

**Comment by ChineSEngineer** [comment]
Thank you for the detailed explanation. I just made a pull request.

**Comment by ChineSEngineer** [comment]
Could you see my pull request? This is my first time making a pull request to other's project. I cannot even set a reviewer for my request. If you can see it please help me approve it.

**Comment by ConnorMulqueen** [comment]
Looks good! I can see it, thanks for the collaboration!

**Comment by ConnorMulqueen** [comment]
To anyone reading this - **ChineSEngineer** wasn't actually the person assigned to this task, there was a misunderstanding explained in Gitter. This issue is still open

**Comment by alexwu422** [comment]
Hi, I'm assigned to this issue and I'm confused because @ChineSEngineer seems to be doing the same issue? It would be great if @ConnorMulqueen can clarify? Thank you!

**Comment by ConnorMulqueen** [comment]
I'm not merging this change into our product, but the collaboration phase is over so I'm closing this issue!
