### ISSUE TITLE
Trivial Bug: Quit button

### ISSUE THREAD

**Issue by pyang3** [ConnorMulqueen/Geesenado#49]
Problem: When you press esc key and quit and click play again the game will start in a paused state.

How to replicate: ESC key > Quit > Play

Image: 
![image](https://user-images.githubusercontent.com/31747401/38060935-f0fc5e50-32ba-11e8-9695-4db33262f2df.png)

**Comment by btackett3** [comment]
+1  This also happened to me when I played the game in the browser via the link provided.  Using Google Chrome.

**Comment by KDub18** [comment]
Thank you, we will look into this.
