### ISSUE TITLE
[Bug] Can't point out the which way the player is facing

### ISSUE THREAD

**Issue by hel1ow0r1d** [ConnorMulqueen/Geesenado#51]
When playing the game, I just hit space to hit the enemy but there's no way of telling if I am directly looking at the enemy or behind me. There are times I would want to hit the enemy behind me, but it keeps shooting in the other direction and I can't change player/object direction with the keyboard. Ability to change the direction which the object is facing would help.

**Comment by jaredgav** [comment]
You use the mouse. There is  youtube tutorial.
