### ISSUE TITLE
[Alpha Testing] Bug: The quit button doesn't do anything.

### ISSUE THREAD

**Issue by joshuaemer** [ConnorMulqueen/Geesenado#86]
OS: Windows 10

Description:
In the pause menu clicking on the QUIT button doesn't do anything.

How to reproduce:
Start the game then pause it.  Click on the QUIT button.

NOTE: This bug was submitted as part of the Alpha Testing section of the Collaboration Phase. It was found on the alpha release of this software.

**Comment by jaredgav** [comment]
Did you find this problem on the Beta Release as well?

**Comment by jaredgav** [comment]
@joshuaemer

**Comment by joshuaemer** [comment]
Windows and I did not test it on the beta.

**Comment by jaredgav** [comment]
Ok it should work. On beta. thanks again.
